CHANGES.rst, src/zc/buildout/easy_install.py, src/zc/buildout/tests.py
See #212 
Fixes #212 
Includes test (that indeed failed initially). Includes fix (of course) and a changelog entry (hurray!).
=> Our VersionConflict handling could result in an UnpackError when rendering

CHANGES.rst, DEVELOPERS.txt, src/zc/buildout/bootstrap.txt, src/zc/buildout/bootstrap_cl_settings.test, src/zc/buildout/buildout.py, src/zc/buildout/buildout.txt, src/zc/buildout/downloadcache.txt, src/zc/buildout/setup.txt, src/zc/buildout/tests.py, src/zc/buildout/update.txt
I copied lelit's #172 pull request so that I could make some adjustments:
- Merge with master.
- A little bit of simplification by treating all three cache dirs the same (which means: creating them at the same time).
=> Slightly improved version of lelit's #172

src/zc/buildout/buildout.py
See discussion on the distutils-dev mailinglist. @wichert said unicode shouldn't be necessary on python 2. So I dived in a bit more and discovered the fix from #250 can be made much simpler.
=> Better, simpler fix than #250

CHANGES.rst, src/zc/buildout/buildout.py, src/zc/buildout/downloadcache.txt
Patch to sort out issue GH-259.
=> Changed os.mkdir to os.makedirs to make it support nested directory creation

CHANGES.rst, src/zc/buildout/easy_install.py, src/zc/buildout/easy_install.txt
This one supersedes #277. The fix is the same, but I added a test and changelog entry.
=> Same as #277, but with test and changelog entry

src/zc/buildout/download.py
Refs #257. Provide a pull request for patch provided in
https://github.com/buildout/buildout/issues/257#issuecomment-159423299
=> Turn proposed patch into a pull request.

DEVELOPERS.txt, src/zc/buildout/buildout.py, src/zc/buildout/buildout.txt
This is related to issue #63, and introduces a simple fix for it, using exisiting code.
=> Simple Fix for 'Extending sections (macros)' in combination with += and -=.

CHANGES.rst, src/zc/buildout/easy_install.py, src/zc/buildout/tests.py
=> Added a hook to enable a soon-to-be-released buildout extension

tox.ini
Set good python version for tox.
=> Update tox versions according to Makefile

doc/getting-started.rst, doc/topics/history.rst, doc/topics/index.rst
This is where, among other things, we say why we use eggs.
=> Motivation, history and Python packaging topic

CHANGES.rst, src/zc/buildout/easy_install.py
=> windows: scripts are implemented with 2 files, avoid burping on that

doc/topics/writing-recipes.rst, setup.py, src/zc/buildout/testing.py, src/zc/buildout/tests.py
Document how to (and not to :)) test recipes.
Also moved some useful functions into testing.
Made some adjustments to ``zc.buildout.testing.Buildout`` to make it more useful for testing ordinary recipes.
=> Testing recipes

src/zc/buildout/easy_install.py
The `unpack_wheel` was blindly trusting the result of `wheel_to_egg()`
and possibly laying zipped eggs in `eggs-directory`.
Fix it to always unpack the result of `wheel_to_egg()` instead.
=> Always unpack what `wheel_to_egg()` generates

doc/topics/optimizing.rst, doc/topics/variables-extending-and-substitutions.rst, src/zc/buildout/buildout.txt, src/zc/buildout/repeatable.txt, src/zc/buildout/tests.py, src/zc/buildout/update.txt, zc.recipe.egg_/src/zc/recipe/egg/README.rst
=> Update tests to work with setuptools 36.

zc.recipe.egg_/CHANGES.rst, zc.recipe.egg_/src/zc/recipe/egg/egg.py
It could fix #429 issue.
PS: This PR is a fixed version of https://github.com/buildout/buildout/pull/431
=> Added sorting of working set used by zc.recipe.egg

CHANGES.rst, doc/reference.rst, doc/topics/variables-extending-and-substitutions.rst, src/zc/buildout/allow-unknown-extras.txt, src/zc/buildout/buildout.py, src/zc/buildout/buildout.txt, src/zc/buildout/easy_install.py, src/zc/buildout/easy_install.txt, src/zc/buildout/tests.py, zc.recipe.egg_/src/zc/recipe/egg/egg.py
=> Add 'allow-unknown-extras'

CHANGES.rst, src/zc/buildout/buildout.py, src/zc/buildout/buildout.txt
for continuous integration
I am pretty happy with the code. I have some doubt about what to do in case of multiline values.
Feedback appreciated.
=> add a `query` command

CHANGES.rst, src/zc/buildout/buildout.py
=> Fix DeprecationWarning about MutableMapping.

.github/workflows/scripts-2.7.cfg, .github/workflows/scripts-3.5.cfg, .github/workflows/scripts-3.6.cfg, .github/workflows/scripts-3.7.cfg, .github/workflows/scripts-versions-2.7.cfg, .github/workflows/scripts.yml, .github/workflows/setuptools-master.yml
build for 2.7 was broken by new release of ``more-itertools``
=> [actions] fix scripts and setuptools-master workflows

.travis.yml
Now that they pass on GitHub Actions
=> run Travis tests in CentOS container

CHANGES.rst, src/zc/buildout/__init__.py, src/zc/buildout/patches.py
by patching `pkg_resources.Distribution`.
=> make install of unpinned setuptools much quicker

CHANGES.rst, src/zc/buildout/patches.py
=> Problem: slow pkg_resources.Distribution.hashcmp

CHANGES.rst, src/zc/buildout/easy_install.py
Solution: show it only once
Closes #512
=> Problem: pip Python2.7 warning displayed too often

src/zc/buildout/buildout.py, src/zc/buildout/easy_install.py, src/zc/buildout/easy_install.txt, zc.recipe.egg_/src/zc/recipe/egg/egg.py
Solution: extract `zc.recipe.egg` code to properly sort
Closes #509
=> Problem: buildout script not sorted

dev.py, src/zc/buildout/easy_install.py, src/zc/buildout/tests/test_extras.py
=> Requirement parse error

.travis.yml, .travis/docker_login_on_non_pull_requests.sh, news/travis-pr.develop
Solution: avoid using encrypted variables when on PR
=> Problem: Travis security on PRs break jobs

.deepsource.toml, dev.py, src/zc/buildout/download.py, src/zc/buildout/easy_install.py, src/zc/buildout/testing.py, src/zc/buildout/tests/__init__.py, src/zc/buildout/tests/test_all.py, zc.recipe.egg_/src/zc/recipe/egg/egg.py, zc.recipe.egg_/src/zc/recipe/egg/tests.py
Hi :wave:, I ran [DeepSource](https://deepsource.io/) analysis on my fork of the repo, and found some [interesting code quality issues](https://deepsource.io/gh/akshgpt7/buildout/) that can improve the general code quality and performance here.
This PR fixes a few of the issues detected.
- Refactor complex statement to use `if` expression.
- Fix dangerous default argument.
- Remove unused imports and reimported modules.
- Refactor unnecessary use of list comprehension.
- Add `.deepsource.toml` file for continuous analysis on bug risks/performance/code-quality issues on new changes.
=> Refactor code quality issues

.gitignore, CONTRIBUTING.rst
I merged `DEVELOPERS.txt` into the the contributing document.
Looking forward to improvements, as writing the contributing document as a pretty new contributor feels a bit awkward :-)
This fixes #548
=> create contributing document

.circleci/config.yml, .github/workflows/centos.yml, .github/workflows/debian-sys.yml, .github/workflows/debian.yml, .github/workflows/python-runners.yml, .github/workflows/scripts-3.10.cfg, .github/workflows/scripts.yml, Makefile, Makefile.configure.Darwin, builds/bare_machines/ci_build.sh, dev.py, setup.py, src/zc/buildout/tests/test_all.py
Solution: add jobs to GH actions and to CircleCI
=> Problem: Python 3.10 not tested on CI

news/589.bugfix, src/zc/buildout/easy_install.py
Solution: check for existence of namespace directories
=> c extension uses namespace without directories

news/592.bugfix, src/zc/buildout/buildout.py, src/zc/buildout/tests/buildout.txt
check value explicitely and open corresponding files
=> honor CLI buildout:extends

.circleci/config.yml, .github/workflows/centos.yml, .github/workflows/debian-sys.yml, .github/workflows/debian.yml, .github/workflows/python-runners.yml, .github/workflows/scripts-3.11.cfg, .github/workflows/scripts-setuptools-head.yml, .github/workflows/scripts.yml, .github/workflows/ubuntu-default.yml, Makefile, dev.py, doc/running-tests.rst, news/cli-extends.bugfix, setup.py, src/zc/buildout/buildout.py, src/zc/buildout/tests/debugging.txt
- Document how to run tests
- Fix cli 'extends'
=> Run tests with 3.11

Makefile, news/634.bugfix, src/zc/buildout/patches.py, src/zc/buildout/tests/buildout.txt, src/zc/buildout/tests/easy_install.txt, src/zc/buildout/tests/update.txt
=> Implements PEP 503
