buildout/buildout

- dev.py
In setuptools < 8.3 pkg_resources.py was a module, so
import pkg_resources
print(pkg_resources.__file__)
would print something like
/home/mg/src/buildout/eggs/setuptools-8.0.4-py2.7.egg/pkg_resources.py
Starting from setuptools 8.3 pkg_resources became a package, so the
above code prints
/home/mg/src/buildout/eggs/setuptools-11.3.1-py2.7.egg/pkg_resources/__init__.py
which means a single os.path.dirname() is no longer sufficient to find
the location of the .egg file/directory.
I'm pretty sure 'setuptools' itself was always a package, so use two
os.path.dirname()s on setuptools.__file__ to find the .egg location more
reliably with both old and new setuptools versions.
Fixes https://github.com/buildout/buildout/issues/227
> Don't assume pkg_resources is a module.

- bootstrap/bootstrap.py
On Windows, `sys.prefix` is a site-package directory, i.e. for a
standard installation `C:\Python27`. The code path for `not
allow_site_packages` removed *everything* from `sys.path` that contains
*any* of the the site-packages directories as reported by
`site.getsitepackages`, which on Windows removes all pathes below
`sys.prefix` from `sys.path`.
> Potential fix for https://github.com/buildout/buildout/issues/217

- src/zc/buildout/downloadcache.txt
- src/zc/buildout/easy_install.txt
- src/zc/buildout/tests.py
- zc.recipe.egg_/src/zc/recipe/egg/README.txt
Recent setuptools versions changed the canonical spelling of release
candidate versions from 'cN' to 'rcN'.  Using the older spelling causes
a UserWarning about the version requiring normalization, and test
failures where the expected output contains a different (normalized)
version number.
For the record, the UserWarning looks like this:
/home/mg/src/buildout/eggs/setuptools-11.3.1-py2.7.egg/setuptools/dist.py:283:
UserWarning: The version specified requires normalization, consider
using '1.2rc1' instead of '1.2c1'.
and the failures can be seen at
https://travis-ci.org/buildout/buildout/jobs/46215472
> Use 'rcN' for release candidate versions in tests

- src/zc/buildout/easy_install.py
If setuptools is installed globally by easy_install then the easy_install.pth gets added to sys.path before PYTHONPATH and the wrong setuptools version is used.
Any chance of a 2.2.6 with this fix included?
> Run easy_install with specified setuptools_version

- bootstrap/bootstrap.py
- src/zc/buildout/bootstrap.txt
For a completely offline install would need to make download_setuptools recognize filesystem paths for download_base.
> Use local ez_setup.py if one exists; add --setuptools-download-base option

- .travis.yml
- CHANGES.rst
- Makefile
Solves #230, a little bit at least.
I adjusted the makefile: the python releases are downloaded and compiled in a directory separate from the compiled results. The compiled results are cached in travis. Keeping the cache small is essential.
The travis config now uses containers ("sudo=false"), which allows us to cache the compiled python packages. This shaves 2-3 minutes off the build.
The time is down from 8-12 minutes to 4-10 minutes. So... most of the time is still in the actual tests.
Technical note: travis doesn't (yet) distinguish caches per environment variable, like we use. So every run, when completed, tries to save its results to the cache. So one of the 5 pythons will get cached as they run at the same time... So someone (probably me) needs to re-start individual builds for …
> Travis speed improvement through caching

- CHANGES.rst
- zc.recipe.egg_/CHANGES.txt
- zc.recipe.egg_/setup.py
- zc.recipe.egg_/src/zc/recipe/egg/custom.py
> Avoid prefixing buildout dir to 'special' rpath elements.

- CHANGES.rst
- src/zc/buildout/buildout.py
- src/zc/buildout/tests.py
Fixes #89 and #148.
The error only occurred on python 2, python 3 is fine. The main cause:
`os.walk()` would return filenames as non-ascii bytestrings. A `' '.join()` would fail with an error. (Or the subsequent `.encode()` call, I don't remember which of the two was an error. We now convert all filenames to unicode. The same approach is used by zest.releaser and it works fine there.
Additionally, the md5 `hash.update()` would fail with non-ascii characters. There's now an explicit call to `.encode('utf-8')`, just like with the file contents, which we already assumed could be non-ascii.
The tests run on both 2 and 3. The original test case failed on 2.x and ran just fine on 3.x the first time it ran on travis.ci, nicely demonstrating that it worked fine on python 3.
Note that there was …
> Buildout no longer breaks on packages with non-ascii filenames in them.

- CHANGES.rst
- DEVELOPERS.txt
- bootstrap/bootstrap.py
- src/zc/buildout/bootstrap.txt
- src/zc/buildout/buildout.py
- src/zc/buildout/buildout.txt
- src/zc/buildout/easy_install.py
Fixed bootstrap: a wrong combined try/except could lead to unintended breakage. In the end I removed the early import of setuptools altogether as it doesn't work well anymore with the newest ez_setup.py files.
The bootstrap phase of buildout itself now removes the develop-eggs directory first. I've grown tired of telling collegues to "remove the develop-eggs/ directory" when they have buildout problems. Some old bootstrap scripts could leave an incorrect `setuptools.egg-link` in there. Same with the `osc.recipe.sysegg` (there's a better version in `syseggrecipe` now that does the right thing). Anyway, removing the directory when bootstrapping is a good safety valve.
> Bootstrap fixes, including develop-eggs removal

- bootstrap/bootstrap.py
Small thing. The help text for `--accept-buildout-test-releases` mentioned the `--version` option which now needs to be `--buildout-version`.
> Fixed bootstrap help text: --buildout-version.

- CHANGES.rst
- src/zc/buildout/easy_install.py
This can give a small speed increase.
Before this, for each dist we would first check if it had a dependency links option, which is almost always the case, but it is usually empty: the package *will* have a dependency_links.txt in its EGG-INFO, but there is only an empty line in it.
When you have a lot of packages and several buildout parts that use them, the dependency links can be checked a lot of times.
On an extended Plone buildout with `use-dependency-links=false`, where get_dist was called over 2500 times, the difference was 0.1 seconds, so not much.  When I/O is slow, the difference could be more noticeable.
Note that actually setting `use-dependency-links` to false, already helps much more.  For this buildout it shaved off 1.5 seconds.
Note that the 0.1 seconds win is because we …
> Check the 'use-dependency-links' option earlier.

- src/zc/buildout/download.py
Behind a proxy, `urllib` does not work with Python2 due to [Python issue
24599](https://bugs.python.org/issue24599).
Instead of using `urllib`, let's implement `urlretrieve` with `urllib2`, which
instead works and leave the Python3 implementation untouched (since that
one works too).
This fixes buildout issue #32.
There's no need to change the `try: except:IOError` block where `urlretrieve` is
used (line 195 in download.py) since the exceptions raised by `urllib2`
are subclasses of `IOError` and will then be caught.
> Enable downloading behind a proxy by using urllib2

- CHANGES.rst
- src/zc/buildout/buildout.py
- src/zc/buildout/extends-cache.txt
Fixes #245 mostly.
The error now prints the cached location of the downloaded file, making it much easier to clean up downloads that went wrong.
> A MissingSectionHeader error now also reports the cached file

- src/zc/buildout/tests.py
fixes the 2 failures at
http://winbot.zope.org/builders/zc_buildout_dev%20py_270_win32%20master/builds/1144/steps/test/logs/stdio
> fix for win32 '#!"python"' vs '#!python' shebang

- buildout.cfg
This only impacts testing.
Note that
VersionConflict: (zc.recipe.testrunner 2.0.0 (/Users/reinout/.buildout/eggs/zc.recipe.testrunner-2.0.0-py2.7.egg), Requirement.parse('zc.recipe.testrunner==1.3.0'))
means you have to remove .installed.cfg. Pinning a recipe version in a 'recipe=' line isn't handy.
> Upgraded version pins

- src/zc/buildout/easy_install.txt
See http://winbot.zope.org/builders/zc_buildout_dev%20py_270_win64%20master/builds/1149/steps/test/logs/stdio
@agroszer: this is the way to fix it, right? Or is there a handier way?
Note: the emails I'm getting help.
> Fixed winbot test. Didn't think about -script and .exe

- CHANGES.rst
- src/zc/buildout/easy_install.py
.exe files are simply excluded from reading. See #279 for background.
> Fix #279 on windows

- CHANGES.rst
- src/zc/buildout/testing.py
I am getting a few test failure on my laptop.  Mac OSX 10.11.6.
The first one is this, made clearer by adding `doctest: +REPORT_UDIFF`:
```
File ".../src/zc/buildout/debugging.txt", line 70, in debugging.txt
Failed example:
print_(system(buildout+" -D", """\
up
p sorted(self.options.keys())
q
"""), end='')  # doctest: +REPORT_UDIFF
Differences (unified diff with -expected +actual):
@@ -1,5 +1,5 @@
Develop: '/sample-buildout/recipes'
Installing data-dir.
-> buildout.py(NNN)__getitem__()
+> buildout.py(NNN)__getitem__()
-> raise MissingOption("Missing option: %s:%s" % (self.name, key))
(Pdb) > /sample-buildout/recipes/mkdir.py(NNN)install()
```
It looks like no real difference. When inspecting this, it turns out that I get a few special characters at the front of the line:
```
Installing …
```
> In the tests, filter out an invisible control character.

- CHANGES.rst
- setup.py
- src/zc/buildout/easy_install.py
When installing an egg to a location that already exists, keep the current location (directory or file).
This can only happen when the location at first did not exist and this changed during the buildout run.  We used to remove the previous location, but this could cause problems when running two buildouts at the same time, when they try to install the same new egg.
Fixes #307.
This is an alternative for pull request #308 , addressing the concern that @leorochael raised there.
> Do not remove an existing egg.

- CHANGES.rst
- LICENSE.txt
- buildout.cfg
- src/zc/buildout/buildout.py
- src/zc/buildout/buildout.txt
- src/zc/buildout/pep425tags.py
- src/zc/buildout/tests.py
that, when true, causes the `ABI tag
<https://www.python.org/dev/peps/pep-0425/#abi-tag>`_ for the buildout
environment to be added to the eggs directory name.
This is useful when switching Python implementations (e.g. CPython
vs PyPI or debug builds vs regular builds), especially when
environment differences aren't reflected in egg names.  It also has
the side benefit of making eggs directories smaller, because eggs
for different Python versions are in different directories.
> Added a buildout option, ``abi-tag-eggs``

- CHANGES.rst
- src/zc/buildout/easy_install.py
- src/zc/buildout/repeatable.txt
- src/zc/buildout/tests.py
Fixed a bug introduced in 2.6.0:
zc.buildout and its dependeoncies were reported as picked even when
their versions were fixed in a ``versions`` section.  Worse, when the
``update-versions-file`` option was used, the ``versions`` section was
updated needlessly on every run.
> Fixes #326

- doc/reference.rst
- doc/topics/bootstrapping.rst
- doc/topics/index.rst
- src/zc/buildout/tests.py
Note that there are additions to the reference section solely to satisfy links from the new bootstrapping topic.
> Bootstrapping topic

- .travis.yml
- Makefile
- doc/getting-started.rst
- doc/topics/bootstrapping.rst
- setup.py
- src/zc/buildout/tests.py
Two main reasons:
- People can follow examples without needing a compiler
- Make these tests run less slowly.
I considered using fake examples, but I think it's good that people can try the examples and have them work.
I took a stab toward enabling parallel execution using layers, but gave up, but I plan to circle back, because the buildout tests take too long to run.
> Lighten doc examples by using bobo rather than ZEO

- src/zc/buildout/easy_install.py
- src/zc/buildout/easy_install.txt
Make it clear from where we're fetching a dist that we don't have installed, reporting the specific URL or the path from inside the download cache.
> easy_install: moar loggin' for fetchin'

- doc/reference.rst
- doc/topics/bootstrapping.rst
- doc/topics/variables-extending-and-substitutions.rst
- src/zc/buildout/buildout.py
- src/zc/buildout/tests.py
- Intentionally didn't document -o, -O and -n
Offline mode is an attractive nuisance.
-n is unlikely to be needed and can be spelled newest=true
- Removed -o, -O and -n from command help.
- Sorted options alphabetically in the reference doc and command help.
- Removed documentation of the log-level option.  It just confuses things.
I seriously doubt that anyone uses it.
> Added reference documentation for command-line options

- buildout.cfg
- src/zc/buildout/easy_install.py
- src/zc/buildout/tests.py
All write access to `easy_install.Installer._env` and all access to `easy_install.Installer._path` are now done through `easy_install.Installer` methods, so that buildout extensions can install subclasses that alter their behaviour.
> Installer: Encapsulate all uses of `._env` and `._path`

- doc/topics/index.rst
- doc/topics/meta-recipes.rst
- setup.py
- src/zc/buildout/buildout.py
- src/zc/buildout/testing.py
- src/zc/buildout/tests.py
This just moves the existing documentation from the buildout package into the manual.
The original test was written as documentation using manuel.
> Meta recipes

- src/zc/buildout/easy_install.py
It's not present in older setuptools versions.
It seems not to be needed since `pkg_resources.Environment.add()` will
sort dists in each project_name according to their version anyway.
Fix: #375
> Drop use of pkg_resources._by_version_descending()

- .gitignore
- CHANGES.rst
- doc/reference.rst
- src/zc/buildout/buildout.py
- src/zc/buildout/buildout.txt
- src/zc/buildout/tests.py
--verbose allows, among others, to find out which values are overridden
when extending cfg files
--section allows to focus on a specific section
> verbose mode and select sections for annotate command

- CHANGES.rst
- src/zc/buildout/buildout.py
This fixes #392 (as far as I can test locally with zc.recipe.cmmi).
Previously under Python 3 (probably prior to 3.6, when dicts became ordered by default) or under Python 2 with ``-R`` or ``PYTHONHASHSEED=random`` the results were undefined because dict
iteration order is undefined.
The value being sorted is complex and defined by pkg_resources.Distribution:
```python
@property
def hashcmp(self):
return (
self.parsed_version,
self.precedence,
self.key,
_remove_md5_fragment(self.location),
self.py_version or '',
self.platform or '',
)
def __hash__(self):
return hash(self.hashcmp)
def __lt__(self, other):
return self.hashcmp < other.hashcmp
...
```
Note that there may be certain circumstances where this will cause existing `.installed.cfg` to be considered outdated spuriously, most likely …
> Sort distributions when computing a signature.

- .coveragerc
- .gitignore
- .travis.yml
- CHANGES.rst
- buildout.cfg
- src/zc/buildout/testing.py
- src/zc/buildout/testing.txt
- tox.ini
Fixes #397.
tox will produce the coverage reports by default.
Travis currently has the coverage disabled because it wants to work in a completely isolated python (can it be changed to invoke tox, maybe?).
Unfortunately because of #398 it's difficult to prove that it works. I have tested it with zopefoundation/zc.recipe.cmmi#2, though, and it does work there.
> Support coverage for subprocess.

- zc.recipe.egg_/CHANGES.rst
- zc.recipe.egg_/setup.py
- zc.recipe.egg_/src/zc/recipe/egg/egg.py
- zc.recipe.egg_/src/zc/recipe/egg/tests.py
- zc.recipe.egg_/src/zc/recipe/egg/working_set_caching.rst
This PR is meant to address the problem discussed here: https://community.plone.org/t/multiple-zope-instances-slow-buildout
Review is much appreciated because I'm new to buildout development (I'm a buildout heavy user, though).
> Fix #153: buildout should cache working set environments

- CHANGES.rst
- src/zc/buildout/buildout.txt
- src/zc/buildout/easy_install.py
- src/zc/buildout/easy_install.txt
- src/zc/buildout/repeatable.txt
PyPI redirects all requests from HTTP to HTTPS by default now so using HTTPS directly avoids the potential for that redirect being modified in flight, helping prevent MITM attacks.
Fixes #114.  The old comments over there aren't applicable any longer.
> Use HTTPS for default PyPI index

- CHANGES.rst
- src/zc/buildout/downloadcache.txt
- src/zc/buildout/easy_install.py
- src/zc/buildout/easy_install.txt
- src/zc/buildout/tests.py
- zc.recipe.egg_/src/zc/recipe/egg/README.rst
For instance when sdist file name and package name had different case.
Integrates patch proposed at https://github.com/buildout/buildout.wheel/issues/10#issuecomment-297661933
Should fix #385 #395
> Fixed: could not install eggs with case issues

- CHANGES.rst
- src/zc/buildout/easy_install.py
- src/zc/buildout/tests.py
Default to setuptools' wheel support instead of failing
Setuptools 38.2.0 suddenly started supporting and downloading wheels.
.whl files would end up in the non-functioning and deprecated unpack_wheel().
The new default ('just use setuptools') works fine.
- If you use an older setuptools, setuptools won't download wheels and the new
code won't be used.
- If you use buildout.wheel, you'll overwrite the unpacker anyway.
Fixes #425
> Install wheels via setuptools, fixes #425

- src/zc/buildout/easy_install.py
- src/zc/buildout/easy_install.txt
- src/zc/buildout/tests.py
- src/zc/buildout/update.txt
- zc.recipe.egg_/src/zc/recipe/egg/api.rst
In easy_install.Installer._get_dist, a package is retrieved and installed in the eggs folder (eg. ~/.buildout/eggs).
Previously, the program would re-scan the environment for changes, check that the newly downloaded package was accessible and return a list of packages (allowing for dependencies) which were installed.  These packages would then be added to the working set.
The problem was that the accessibility check was done against a working set that did not yet reflect the newly downloaded packages.  This was not generally a problem, except where a conflicting package was already installed (for example in sdist).  In such a case, buildout would fail, reporting a version conflict, but running buildout directly afterward would succeed because the environment and working set would contain …
> Fix race condition with working set not reflecting reality during integrity check.

- src/zc/buildout/buildout.py
Fixes `buildout.py:574: ResourceWarning: unclosed file <_io.TextIOWrapper...>`
> properly close resources

- CHANGES.rst
- src/zc/buildout/buildout.py
Use case: buildout that uses mr.developer. When you bootstrap it with ye olde bootstrap.py, it starts up with setuptools 33.1.1. 
When installing the mr.developer extension, it upgrades setuptools to 38.5.2 (as we've pinned that version). With the new buildout 2.11 functionality, installed packages are immediately added to the working set.
After installing the extension, the `maybe_upgrade()` function it called. This checked the working set if it was up to date with the currently installed packages. With buildout 2.11, this was always the case.
I've changed the check to look at the buildout/setuptools install locations that were detected when first loading the `easy_install.py` module.
> Correctly detect upgrade with extension that depends on setuptools

- CHANGES.rst
- src/zc/buildout/easy_install.py
`pkg_resources.SetuptoolsVersion` got deprecated in `setuptools` `v39.0.0`.
Moved on using stable and recommended `pkg_resources.parse_version`
function that does the same. For more details on the topic
see http://setuptools.readthedocs.io/en/latest/history.html#v39-0-0.
> Fix for #442 issue

- CHANGES.rst
- doc/getting-started.rst
- doc/reference.rst
- doc/topics/bootstrapping.rst
- doc/topics/extensions.rst
- doc/topics/writing-recipes.rst
- src/zc/buildout/allowhosts.txt
- src/zc/buildout/buildout.txt
- src/zc/buildout/easy_install.py
- src/zc/buildout/easy_install.txt
- src/zc/buildout/repeatable.txt
According to a blog post of [Sumana Harihareswara](https://www.harihareswara.net/sumana/2018/04/11/0) https://pypi.python.org/ will be a redirect to https://pypi.org by April 16th.
I changed all occurrences (besides the ones in `HISTORY.rst`) of `pypi.python` to the new URLs.
> Use the new PyPI at https://pypi.org/.

- CHANGES.rst
- src/zc/buildout/easy_install.py
- src/zc/buildout/tests.py
Fixes #451.
I tested this manually with the reproduction instructions in #451 but I haven't added a unit test (or succeeded in running buildouts existing unit tests locally yet either, actually).
> Compare using Distribution.parsed_version to account for normalization.

- src/zc/buildout/easy_install.py
- src/zc/buildout/rmtree.py
1. Simply also re-use zc.buildout.rmtree in easy_install.py.
2. Additionally try even harder (as mentioned in zc.buildout's rmtree) removing folders, for instance, when getting "WindowsError: [Error 32]", which only happens "sometimes" and nobody knows why (e.g. antivirus is deactivated).
Traceback (most recent call last):
File "C:\platform\15.3.auto\lib\site-packages\zc.buildout-2.11.0-py2.7.egg\zc\buildout\buildout.py", line 2123, in main
getattr(buildout, command)(args)
File "C:\platform\15.3.auto\lib\site-packages\zc.buildout-2.11.0-py2.7.egg\zc\buildout\buildout.py", line 796, in install
installed_files = self[part]._call(recipe.install)
File "C:\platform\15.3.auto\lib\site-packages\zc.buildout-2.11.0-py2.7.egg\zc\buildout\buildout.py", line 1553, in _call
return f()
File …
> fix #295: temporary egg files are created as read only and can't be deleted with shutil on Windows.

- Makefile
- doc/topics/bootstrapping.rst
- setup.py
- src/zc/buildout/bootstrap.txt
- src/zc/buildout/bootstrap_cl_settings.test
- src/zc/buildout/buildout.py
- src/zc/buildout/buildout.txt
- src/zc/buildout/configparser.py
- src/zc/buildout/configparser.test
- src/zc/buildout/download.py
- src/zc/buildout/easy_install.py
- src/zc/buildout/repeatable.txt
- src/zc/buildout/rmtree.py
- src/zc/buildout/testing.py
- src/zc/buildout/tests.py
- src/zc/buildout/windows.txt
- tox.ini
- zc.recipe.egg_/setup.py
- zc.recipe.egg_/src/zc/recipe/egg/egg.py
- zc.recipe.egg_/src/zc/recipe/egg/tests.py
On Python 3, these made the build output very hard to read (e.g., https://travis-ci.org/buildout/buildout/jobs/394026829)
On Python 3.7, these could actually break the doctests.
Closing the files should get us closer to being able to pass the tests with PyPy.
> Fix most Deprecation and Resource warnings.

- CHANGES.rst
- src/zc/buildout/buildout.py
- src/zc/buildout/debugging.txt
When buildout encounter an error, program exists with error code 1, this
should also be the case when exiting from a debugger session when
running with -D option.
> debugger: Exit with error code on debugged error

- src/zc/buildout/easy_install.py
- src/zc/buildout/testing.py
- src/zc/buildout/tests.py
Fixes #466.
This is #476 by @lrowe + fixed tests by @mgedmin.
Maybe this PR can be merged because the warnings produced by `buildout` are daily annoying me.
> Avoid DeprecationWarning: 'U' mode is deprecated (Version 2)

- src/zc/buildout/easy_install.py
Python 3.7 began warning about open's 'U' mode. Universal newline mode (newline=None) is default in Python 3 so avoid specifying it on Python 3.
Fixes #466.
I believe this is safe even when executable is set to python2 but buildout is run with python3 since inside easy_install.py it is the sys.executable which is used (suggesting that easy_install is being run under the specified executable.)
> Avoid DeprecationWarning: 'U' mode is deprecated

- src/zc/buildout/testing.py
> Fix simple typo: expecially -> especially

- .github/workflows/Makefile
- .github/workflows/scripts.cfg
- .github/workflows/scripts.yml
- .github/workflows/setuptools-master.yml
Travis builds are broken. So we are not warned, among others, about changes in setuptools.
`setuptools 42.0.1` breaks our tests. See #493 
I also made smoke tests.
> Use Github Actions for smoke tests

- src/zc/buildout/easy_install.py
Solution: sys.exit when pip install fails
fixes #513
> Problem: missing error handling leads to IndexError

- CHANGES.rst
- src/zc/buildout/easy_install.py
- zc.recipe.egg_/src/zc/recipe/egg/README.rst
Solution: Warn when a script name passed in 'scripts' argument of easy_install.scripts
is not defined in egg entry points.
10 years old patch 😬
> Problem: Does not complain for typo in 'scripts'

- src/zc/buildout/buildout.py
- src/zc/buildout/tests.py
When a recipe is developed in a git working copy, .git administrative
database folder should be ignored, like we did with CVS and svn.
fixes #522
> ignore git when computing signature of a recipe develop egg

- CHANGES.rst
- dev.py
The bootstrap process uses `get-pip.py`, which in its latest version,
tries to bootstrap a Python 3 only version of pip.
We need to pass in a separate URL for a Python 2.7 compatible version of get-pip.py.
This should fix #546
> Fix bootstrapping for Python 2.7

- src/zc/buildout/buildout.py
Solution: use environment variable instead
See #515
> Problem: mr.developer broken by CLI arg to avoid endless loop

- CHANGES.rst
- setup.py
setuptools is now pinned to <52.
setuptools version 52 broke support for easy_install
https://github.com/pypa/setuptools/blob/main/CHANGES.rst#breaking-changes-1
info below is now invalid
```
setuptools>=42.0.1 is necessary so buildout can download e.g. latest
versions of `cryptography`, possibly related to
https://github.com/pyca/cryptography/blob/main/CHANGELOG.rst#34---2021-02-07
also see
https://github.com/pypa/setuptools/blob/main/CHANGES.rst#v4201
```
This fixes #543
> update setuptools requirements

- news/556.bugfix
- src/zc/buildout/easy_install.py
Solution: create missing dir before `os.rename`
See #556
> Problem: egg installation fails with FileNotFoundError

- news/483.feature
- src/zc/buildout/buildout.py
- src/zc/buildout/tests/allowhosts.txt
- src/zc/buildout/tests/extends-cache.txt
- src/zc/buildout/tests/test_all.py
- src/zc/buildout/tests/update.txt
> Improve warning message when a section contains unused options.

- .deepsource.toml
- .github/workflows/scripts-versions-2.7.cfg
- CHANGES.rst
- src/zc/buildout/buildout.py
- src/zc/buildout/configparser.test
If you use `zc.buildout` 2.13.7 to install [Plone 6.0.0b2](https://community.plone.org/t/plone-6-0-0b2-released/15643/2?u=mauritsvanrees) you will get an error:
NameError: name 'python310' is not defined
See [another example of the same problem](https://github.com/collective/collective.honeypot/pull/8#issuecomment-1244568342).
Easy buildout config to try, on any Python version:
```
[buildout]
parts = test
[test]
recipe = zc.recipe.egg
eggs = build
[test:python310]
recipe = zc.recipe.egg
eggs = requests
```
This PR should fix it by supporting five more Python versions. I guess this should be enough for the foreseen lifetime of buildout 2.x. :-)
I wonder if there are better ways to solve this, but for now this should do the trick.
> Support python310-315 in conditional section expressions. [2.x]

- .github/workflows/centos.yml
- .github/workflows/debian-sys.yml
- .github/workflows/debian.yml
- .github/workflows/python-runners.yml
Fixes issue #617.
Copied from the zopefoundation repositories.
See https://github.com/zopefoundation/meta/issues/145 and the final version with single quotes at [meta](https://github.com/zopefoundation/meta/blob/9c24f7380973de989c5132ec9f28fa71f1397f20/config/c-code/tests.yml.j2#L93).
I also added `workflow_dispatch` to allow to run these workflows manually from the Actions tab.
> Prevent running gh-actions twice for push/pull.

- news/613.bugfix
- src/zc/buildout/patches.py
Fixes https://github.com/buildout/buildout/issues/613.
Note: we are patching `process_url` from `setuptools`. The existing comment says that this method was copied over from setuptools 46.1.3. I was wondering, so I checked: the method is still the same in latest setuptools.  And it is largely unchanged since setuptools 42.0.2. So for that part we should still be compatible with quite a long range of setuptools versions.
This PR also expands the warning that is printed when the patch fails. Until now it said "Requires-Python support missing." There was no indication that this was a message from buildout, so I assumed this was something from a newer setuptools or pip, and it warned about a package that did not have a `requires_python` in its `setup.py/cfg`. Now it should be clear that it is …
> Make compatible with pip 22.2+, restoring Requires-Python patch

- news/621.bugfix
- src/zc/buildout/configparser.py
The previous code went wrong depending on which pip/setuptools/wheel version you had.
> Fixed import of packaging.markers.

- .circleci/config.yml
- .github/workflows/run-tests.yml
- .github/workflows/scripts-setuptools-head.yml
- Makefile
- builds/bare_machines/ci_build.sh
- dev.py
- doc/topics/optimizing.rst
- doc/topics/variables-extending-and-substitutions.rst
- news/35.breaking
- news/647.bugfix
- news/648.bugfix
- setup.py
- src/zc/buildout/_compat.py
- src/zc/buildout/configparser.py
- src/zc/buildout/easy_install.py
- src/zc/buildout/patches.py
- src/zc/buildout/testing.py
- src/zc/buildout/tests/__init__.py
- src/zc/buildout/tests/test_all.py
- src/zc/buildout/utils.py
This is with setuptools 70.
Done by adding a compatibility module that tries to import `packaging` from several places. 
Fixes https://github.com/buildout/buildout/issues/648
This should partially fix GitHub Actions, but they were already failing for a long time due to other reasons.
> Fix ImportError: cannot import name 'packaging' from 'pkg_resources'

- src/zc/buildout/buildout.py
- src/zc/buildout/configparser.py
- src/zc/buildout/tests/buildout.txt
- src/zc/buildout/tests/configparser.test
Issue #656 : My earlier patch did not take into account all the various combinations of operators that could occur in multiple sections. This one does, and handles all of them properly. It also calls _update_section to ensure that any +=/-= operators are applied properly. 
The problem in Issue #641 needs to be dealt with for conditional sections, and occurs in the same place as the _update_section patch for 656, so it is included here.
I've also applied these changes to the latest buildout master branch. Tests have been updated, and are all passing under both Python 2.7 and 3.9 on my system.
> Updated Patches for Issues 641 and 656

- src/zc/buildout/buildout.py
- src/zc/buildout/tests/test_increment.py
Process extends in order, otherwise variable settings can be applied out of order.
Fixes #176
Closes #177
Fixes #629.
I first submitted this patch almost 10 years ago. We run a **very** complex buildout, and this breaks it.  I've been patching buildout 2, for almost 10 years, with no issues. The application of this patch to buildout 3 was very straightforward.  I believe this fix is stable, and would really appreciate seeing it incorporated. 
Thank you.
> Issues 176 and 629: Process extends in order

- Makefile
This modifies the test command in the Makefile so it runs again on Python 2.7.
> Fix broken Python 2.7 test command - issue #661

- src/zc/buildout/buildout.py
- src/zc/buildout/tests/repeatable.txt
Resolves Issue #577, where versions are not pinned when processing the buildout section, and any prerequisite sections that are processed with it.
I can also create a patch for the buildout 2.x branch, if that is actively being maintained.
> Pin versions when processing buildout section

- CHANGES.rst
- doc/reference.rst
- old-tutorial/tutorial.fr.txt
- old-tutorial/tutorial.txt
- specifications/README.txt
- specifications/repeatable.txt
- src/zc/buildout/buildout.py
- src/zc/buildout/tests/buildout.txt
- src/zc/buildout/tests/debugging.txt
- src/zc/buildout/tests/dependencylinks.txt
- src/zc/buildout/tests/runsetup.txt
- src/zc/buildout/tests/test_increment.py
- zc.recipe.egg_/README.rst
- zc.recipe.egg_/src/zc/recipe/egg/api.rst
My editor is configured to remove trailing whitespace on save. Several files that I touched lately would in this way get irrelevant changes, that I then mostly undid (using `git add --patch`) to avoid distracting reviewers. But now I removes all trailing whitespace.
That *did* lead to one test failure, which I fixed by normalizing whitespace in one doctest. Failure was (:
```
File "/Users/maurits/community/buildout/venvs/3.8/src/zc/buildout/tests/test_increment.py", line 375, in zc.buildout.tests.test_increment.no_default_with_extends_increment_in_base2_and_base3
Failed example:
print_(system(buildout+' annotate buildout'), end='')
Expected:
<BLANKLINE>
Annotated sections
==================
<BLANKLINE>
[buildout]
...
extensions=
demo2
demo3
IMPLICIT_VALUE
+=  base2.cfg
+=  base3.cfg
... …
```
> Nuke trailing white space.

- zc.recipe.egg_/src/zc/recipe/egg/custom.rst
This mentionned a zip_safe warning that is no longer emitted.
> remove an outdated note in custom.rst

- .github/workflows/run-tests.yml
- news/7581.bugfix
- news/7581.develop
- news/7581.feature
- src/zc/buildout/easy_install.py
- src/zc/buildout/testing.py
- src/zc/buildout/tests/easy_install.txt
I suspect 75.8.1 from yesterday will break for us due to changes in wheel names. Indeed this seems the case locally.  With 75.8.0 from early January I expect all is still fine.
[Update: original title was "Test with latest setuptools 75.8.0 and 75.8.1, and with pip 25.0.1."  Now I have updated the PR to test with latest 75.8.2.]
> Test with latest setuptools 75.8.2, and with pip 25.0.1.

- news/681.bugfix
- src/zc/buildout/buildout.py
This depends on your `setuptools` version.
Additionally, check if we need to upgrade due to the new `packaging` dependency.
Fixes https://github.com/buildout/buildout/issues/681
> Fix error finding zc.buildout dist in upgrade check.

- news/682.bugfix
- src/zc/buildout/patches.py
Let this use the code from `setuptools` 75.8.2, if the currently used version is older. This is better at finding installed distributions.
Fixes https://github.com/buildout/buildout/issues/683
> Patch the find method from pkg_resources.WorkingSet.

- news/686.bugfix
- src/zc/buildout/easy_install.py
This helps for wheels of namespace packages created with `setuptools` 75.8.1 or higher. For namespace package we need a dot instead of an underscore in the resulting egg name.
Fixes https://github.com/buildout/buildout/issues/686
> If needed, copy and rename wheels before making an egg out of them.

- .github/workflows/run-tests.yml
This is in the first batch of jobs where we test a range of setuptools versions. On some following jobs we still use 75.8.2.
> Test with setuptools 75.9.1 and 76.0.0.

- src/zc/buildout/patches.py
Calling `patch_PackageIndex()` might fail due to changes in pip/setuptools.  You can try out this situation by commenting out the `patch_PackageIndex()` call.
Then you get an error when running buildout:
```
Traceback (most recent call last):
File "/Users/maurits/community/buildout/dev.py", line 27, in <module>
import zc.buildout.easy_install
File "/Users/maurits/community/buildout/src/zc/buildout/__init__.py", line 38, in <module>
import zc.buildout.patches  # NOQA
File "/Users/maurits/community/buildout/src/zc/buildout/patches.py", line 263, in <module>
patch_interpret_distro_name()
File "/Users/maurits/community/buildout/src/zc/buildout/patches.py", line 260, in patch_interpret_distro_name
setuptools.package_index.interpret_distro_name = interpret_distro_name
AttributeError: module …
```
> Fix patch_interpret_distro_name to work when patch_PackageIndex fails

- Makefile
- buildout.cfg
- news/675.tests
- pyproject.toml
- src/zc/buildout/testing.py
- src/zc/buildout/tests/__init__.py
- src/zc/buildout/tests/dependencylinks.txt
- src/zc/buildout/tests/downloadcache.txt
- src/zc/buildout/tests/easy_install.txt
- zc.recipe.egg_/CHANGES.rst
- zc.recipe.egg_/setup.py
- zc.recipe.egg_/src/zc/recipe/egg/README.rst
- zc.recipe.egg_/src/zc/recipe/egg/custom.rst
- zc.recipe.egg_/src/zc/recipe/egg/tests.py
- zc.recipe.egg_/src/zc/recipe/egg/working_set_caching.rst
We have not run the `zc.recipe.egg` tests in a long time, maybe even years.  And they fail locally.
This is work in progress, help needed, and I probably won't continue on it this year.
> Test zc.recipe.egg

- news/700.bugfix
- setup.py
Needed because we use the `utils.is_normalized_name` function. Fixes https://github.com/buildout/buildout/issues/700
> Require at least `packaging` version 23.2.

- news/634.bugfix
- src/zc/buildout/patches.py
- src/zc/buildout/tests/easy_install.txt
Since version 4.1.5 we first request normalized package url on PyPI servers, but a subsequent check needed a fix.
Sample output without this fix:
```
$ bin/buildout
...
root: Reading https://pypi.org/simple/zope-testrunner/
root: Reading https://pypi.org/simple/zope.testrunner/
Updating test.
root: Reading https://pypi.org/simple/zc-recipe-deployment/
root: Reading https://pypi.org/simple/zc.recipe.deployment/
root: Reading https://pypi.org/simple/zc-zdaemonrecipe/
root: Reading https://pypi.org/simple/zc.zdaemonrecipe/
root: Reading https://pypi.org/simple/zdaemon/
root: Reading https://pypi.org/simple/manuel/
root: Reading https://pypi.org/simple/six/
root: Reading https://pypi.org/simple/zconfig/
root: Reading https://pypi.org/simple/webob/
root: Reading …
```
> Prevent getting package pages twice.

- news/689.bugfix
- news/695.bugfix
- src/zc/buildout/easy_install.py
Use this for naming the egg that gets created after installing a wheel or after doing a pip install of a source dist. This fixes issue #695.
This replaces PR #696.
Also: use the canonical name of a package when checking for a version constraint. This fixes issue #689.
Combined, this fixes problems for dependencies of packages that were built by `hatchling`.
<s>Internal detail: changed `_maybe_copy_and_rename_wheel` to do only that: maybe copy and rename a wheel, and return that new wheel. Previously, `_move_to_eggs_dir_and_compile` would call this function, and if a rename was indeed needed, it would call `_move_to_eggs_dir_and_compile` with the new wheel and then return the egg. Now this function simply replaces one dist with another, and then `_move_to_eggs_dir_and_compile` continues …
> Get actual project name from dist.

- news/1013.bugfix
- src/zc/buildout/patches.py
PyPI is having issues right now.  Sometimes I get a timeout, which is reported correctly. Other times I get an `HTTP Error 503: Service Unavailable`.  This is not reported, so you have no idea of the cause when later on this leads to a DistributionNotFound.
See https://github.com/plone/buildout.coredev/pull/1013#issuecomment-2785929350
> Log all http errors when processing package url.

- news/705.tests
- prepare.sh
Otherwise, when combining an older `setuptools` with a newer `wheel` version, the `bdist_wheel` command exists in neither of these packages.
Fixes https://github.com/buildout/buildout/issues/705
Note: with newer setuptools, our script does not guarantee that you actually get the latest `wheel` package.  I expected this, but this may depend on what you already have installed in your main Python install.
> Use wheel 0.45.1 when testing with setuptools older than 70.1.0.

- .github/workflows/Makefile-scripts
- news/609.bugfix
- prepare.sh
- src/zc/buildout/easy_install.py
- src/zc/buildout/tests/easy_install.txt
The override only changes the result on Mac: other platforms seem not affected.
This replaces my PRs #707 and #709.
Two minor other changes in here:
* Added some `logger.debug` lines in `_move_to_eggs_dir_and_compile`.
* Added option to use uv for creating the test environment by setting environment variable USE_UV a non-empty value.  We don't use this in our current test setup on GitHub Actions though.
See original report by Jens Vagelpohl a few years ago for setuptools: https://github.com/pypa/setuptools/issues/3687
And his comment in zopefoundation/meta explains well what happens from the standpoint of Buildout:
https://github.com/zopefoundation/meta/issues/181#issuecomment-1757558915
Nowadays, the same can happen with a Python installed by uv, as I saw today:
```
% bin/zopepy
>>> …
```
> Override pkg_resources.Environment.can_add to have better results on Mac

- news/713.bugfix
- src/zc/buildout/easy_install.py
Fixes https://github.com/buildout/buildout/issues/713
> Fix error get_win_launcher not found on Windows on setuptools 80.3+.
